<div dir="ltr">


<b> {{$nombre}}, Durante este mes y solo por amor y amistad, tenemos una sorpresa para ti</b>&nbsp;<img goomoji="1f381" data-goomoji="1f381" style="margin:0 0.2ex;vertical-align:middle;max-height:24px" alt="🎁" src="https://mail.google.com/mail/e/1f381" data-image-whitelisted="" class="CToWUd">


<br><br>

<img goomoji="1f4e2" data-goomoji="1f4e2" style="margin:0 0.2ex;vertical-align:middle;max-height:24px" alt="📢" src="https://mail.google.com/mail/e/1f4e2" data-image-whitelisted="" class="CToWUd">&nbsp;<b>MAMOPLASTIA DE AUMENTO CON TÉCNICA DE CUÑAS®</b>&nbsp;<img goomoji="1f4e2" data-goomoji="1f4e2" style="margin:0 0.2ex;vertical-align:middle;max-height:24px" alt="📢" src="https://mail.google.com/mail/e/1f4e2" data-image-whitelisted="" class="CToWUd"><br><br>• Mayor proyección<br>• Reduce lateralización<br>• Rejuvenece la apariencia<br>• Mejor centralización en el seno<br><br><br><br>¡No esperes más para lucir el cuerpo que siempre has deseado y en manos del especialista <b>Daniel Correa!</b>⚕️✅<br>Escríbenos ahora mismo y pide tu cita de valoración diligenciando el formulario web&nbsp;<img goomoji="1f310" data-goomoji="1f310" style="margin:0 0.2ex;vertical-align:middle;max-height:24px" alt="🌐" src="https://mail.google.com/mail/e/1f310" data-image-whitelisted="" class="CToWUd">&nbsp;<a href="https://bit.ly/2Z2V4k1" target="_blank" data-saferedirecturl="https://www.google.com/url?q=https://bit.ly/2Z2V4k1&amp;source=gmail&amp;ust=1600544606986000&amp;usg=AFQjCNFmD6ylqNDDtA8JHIS01c6ZUr5EzQ">https://bit.ly/2Z2V4k1</a><br><br>También puedes valorarte desde la comodidad de tu casa a través de tu teléfono Adroid con la apliación <b>TeleSaludApp</b><br>• Descargala aquí&nbsp;<img goomoji="1f4f2" data-goomoji="1f4f2" style="margin:0 0.2ex;vertical-align:middle;max-height:24px" alt="📲" src="https://mail.google.com/mail/e/1f4f2" data-image-whitelisted="" class="CToWUd">&nbsp;<a href="https://bit.ly/34UcUql" target="_blank" data-saferedirecturl="https://www.google.com/url?q=https://bit.ly/34UcUql&amp;source=gmail&amp;ust=1600544606986000&amp;usg=AFQjCNGJ1MOXyHctQNLfy5BeuvG--feZhg">https://bit.ly/34UcUql</a><br><br>• Válido por este mes<br></div>
    <div dir="ltr"><br></div>


    <div dir="ltr"><div style="text-align:center"><img src="https://danielandrescorreaposadacirujano.com/wp-content/uploads/2020/08/WhatsApp-Image-2020-09-18-at-13.26.48-1.jpeg" alt="WhatsApp Image 2020-09-18 at 13.26.48.jpeg" width="305" height="542" data-image-whitelisted="" class="CToWUd a6T" tabindex="0"><div class="a6S" dir="ltr" style="opacity: 0.01; left: 403px; top: 910px;"><div id=":6mg" class="T-I J-J5-Ji aQv T-I-ax7 L3 a5q" role="button" tabindex="0" aria-label="Descargar el archivo adjunto WhatsApp Image 2020-09-18 at 13.26.48.jpeg" data-tooltip-class="a1V" data-tooltip="Descargar"><div class="aSK J-J5-Ji aYr"></div></div><div id=":6mh" class="T-I J-J5-Ji aQv T-I-ax7 L3 a5q" role="button" tabindex="0" aria-label="Guardar el archivo adjunto WhatsApp Image 2020-09-18 at 13.26.48.jpeg en Drive" data-tooltip-class="a1V" data-tooltip="Agregar a Drive"><div class="wtScjd J-J5-Ji aYr XG"><div class="T-aT4" style="display: none;"><div></div><div class="T-aT4-JX"></div></div></div></div></div><div class="yj6qo"></div><div class="adL"><br></div></div></div>


